services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=polls_db
      - POSTGRES_USER=polls_user
      - POSTGRES_PASSWORD=polls_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-that-is-long-and-random
      - DEBUG=1
      - DB_NAME=polls_db
      - DB_USER=polls_user
      - DB_PASSWORD=polls_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
